# Generated by Django 4.2.30 on 2026-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_certification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("experience_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.CharField(blank=True, max_length=100)),
                ("end_date", models.CharField(blank=True, max_length=100)),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
    ]
