# Generated by Django 4.2.30 on 2026-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="reason",
            field=models.CharField(
                choices=[
                    ("internship", "Internship opportunity"),
                    ("job", "Job opportunity"),
                    ("collaboration", "Project collaboration"),
                    ("networking", "Networking"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(default="General inquiry", max_length=200),
        ),
    ]
